zapLog:
    development: true
    disableCaller: true
    disableStacktrace: true
    zapCores:
        - level: debug
          encoding: console
          name: console-output
          layout: "2006-01-02 15:04:05.000"
          customConfig:
            timeKey: time
            levelKey: level
            nameKey: logger
            callerKey: caller
            messageKey: msg
            functionKey: ""
            stacktraceKey: stacktrace
          outputPath: stdout
gormDB:
    mysqlDB:
        path: ""
        host: 127.0.0.1
        port: "23306"
        user: ""
        password: "7777777777777"
        database: ""
        maxOpenConns: 0
        maxIdleConns: 0
        connMaxLifeTime: 0
        prefix: ""
        singular: false
        enableLog: false
        logMode: ""
        driver: ""
    sqlLiteDB:
        path: ""
        host: ""
        port: ""
        user: ""
        password: ""
        database: ""
        maxOpenConns: 0
        maxIdleConns: 0
        connMaxLifeTime: 0
        prefix: ""
        singular: false
        enableLog: false
        logMode: ""
        driver: ""
